import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Privacy Policy - sencodev",
  description: "Privacy policy and data protection information for sencodev users",
}

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-900 py-24">
      <div className="container mx-auto px-4 max-w-4xl">
        <h1 className="text-4xl font-bold mb-8 text-slate-900 dark:text-white">Privacy Policy (Datenschutzerklärung)</h1>
        
        <div className="bg-white dark:bg-slate-800 rounded-lg p-8 shadow-sm">
          <div className="prose prose-slate dark:prose-invert max-w-none">
            <p className="bg-yellow-50 dark:bg-yellow-900/20 p-4 rounded border border-yellow-200 dark:border-yellow-800">
              <strong>⚠️ Legal Template</strong><br />
              This privacy policy template needs to be reviewed and customized by a legal professional to ensure GDPR compliance and accuracy for your specific business operations.
            </p>
            
            <h2>1. Data Protection at a Glance</h2>
            
            <h3>General Information</h3>
            <p>
              The following information provides an overview of what happens to your personal data when you visit this website. Personal data is any data that can personally identify you.
            </p>
            
            <h3>Data Collection on This Website</h3>
            <h4>Who is responsible for data collection on this website?</h4>
            <p>
              Data processing on this website is carried out by the website operator. You can find the operator's contact details in the "Contact" section of this privacy policy.
            </p>
            
            <h4>How do we collect your data?</h4>
            <p>
              Your data is collected in various ways. On the one hand, this is data that you provide to us. This can be data that you enter in a contact form, for example. Other data is collected automatically by our IT systems when you visit the website.
            </p>
            
            <h2>2. General Information and Mandatory Information</h2>
            
            <h3>Data Protection</h3>
            <p>
              The operators of these pages take the protection of your personal data very seriously. We treat your personal data confidentially and in accordance with the statutory data protection regulations and this privacy policy.
            </p>
            
            <h3>Contact</h3>
            <p>
              If you have questions about data protection, please write to us at:<br />
              Email: [contact@sencodev.com]<br />
              Address: [To be filled from business registration]
            </p>
            
            <h2>3. Data Collection on This Website</h2>
            
            <h3>Cookies</h3>
            <p>
              Some of our web pages use cookies. Cookies do not harm your computer and do not contain viruses. Cookies help make our website more user-friendly, efficient, and secure.
            </p>
            
            <h3>Server Log Files</h3>
            <p>
              The website provider automatically collects and stores information in server log files, which your browser automatically transmits to us. These are:
            </p>
            <ul>
              <li>Browser type and browser version</li>
              <li>Operating system used</li>
              <li>Referrer URL</li>
              <li>Host name of the accessing computer</li>
              <li>Time of server request</li>
              <li>IP address</li>
            </ul>
            
            <h3>Contact Form</h3>
            <p>
              If you send us inquiries via the contact form, your details from the inquiry form, including the contact details you provide there, will be stored by us for the purpose of processing the inquiry and in case of follow-up questions.
            </p>
            
            <h2>4. Analytics and Advertising</h2>
            
            <h3>Google Analytics</h3>
            <p>
              This website uses Google Analytics, a web analytics service provided by Google Inc. ("Google"). The information generated by the cookie about your use of this website is usually transmitted to a Google server in the USA and stored there.
            </p>
            
            <h2>5. Your Rights</h2>
            
            <p>You have the following rights:</p>
            <ul>
              <li>Right of access to your personal data</li>
              <li>Right to rectification of inaccurate personal data</li>
              <li>Right to erasure of your personal data</li>
              <li>Right to restriction of processing</li>
              <li>Right to data portability</li>
              <li>Right to object to processing</li>
              <li>Right to withdraw consent</li>
            </ul>
            
            <h2>6. Contact Information</h2>
            <p>
              If you have questions about this privacy policy or about data protection in general, please contact us at:<br />
              <strong>Email:</strong> [privacy@sencodev.com]<br />
              <strong>Postal Address:</strong> [To be filled]
            </p>
            
            <p className="text-sm text-slate-600 dark:text-slate-400 mt-8">
              Last updated: [Date to be filled]
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}